Lecture02
nobuyuki-odajima/raisetech-live2-demo2 pull request #1
Opened 2023-01-22 14:37 UTC by nobuyuki-odajima

AWS第二回課題を提出いたしますのでご確認をよろしくお願いいたします。

2023-01-22 15:47 UTC, MasatoshiMizumoto requested changes
こちら確認してみてください！

2023-01-22 15:47 UTC, MasatoshiMizumoto commented on lecture2.md
> +#AWS第二回講義
見出しが正しく設定されてないかもですね！

2023-01-22 15:47 UTC, MasatoshiMizumoto commented on lecture2.md
> +*READMEにしていたのでやり直しとなってしまいました。
コチラも書き方確認してみてください！
```suggestion
* コマンドも初めてのため、少しづつ理解をしながら進めた。
* ようやくできたと思ったら、Markdownのファイルでなく、
* READMEにしていたのでやり直しとなってしまいました。
```

2023-01-22 15:47 UTC, MasatoshiMizumoto commented on lecture2.md
> +-Markdownについて
書き方確認してみてください！
```suggestion
- バージョン管理システムのGithubの流れ
- 実際のチームでの運用について
- Markdownについて
```

2023-01-28 00:24 UTC, nobuyuki-odajima commented on lecture2.md
> +#AWS第二回講義
確認していただきまし得てありがとうございます。
スペースが足りなかったんですね。
修正して再度プルリクエストをすればいいでしょうか

2023-02-17 02:26 UTC, MasatoshiMizumoto commented on lecture2.md
> +#AWS第二回講義
これだけまだ変わってないので変更分をコミット＆pushしてください！
新規プルリクエストしなくてもいいです！

2023-02-18 23:57 UTC, closed without merging